select * from productos;
CREATE TABLE productos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    nombre VARCHAR2(100) NOT NULL,
    precio NUMBER(10, 2) NOT NULL
);

INSERT INTO productos (nombre, precio) VALUES ('Galleta', 5.99);

DROP TABLE productos;

